name: grocery_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.4.0
  http: ^1.1.2
  flutter_riverpod: ^2.4.9
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.1.4
  flutter_lints: ^3.0.1
  build_runner: ^2.2.0
flutter:
  uses-material-design: true
